/**
 * Config API
 * Collection of Configuration Endpoints
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: mstevens@atlan-tics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddConfigItems400ResponseErrors } from './addConfigItems400ResponseErrors';


export interface AddConfigItems400Response { 
    message?: string;
    errors?: AddConfigItems400ResponseErrors;
}

