/**
 * Config API
 * Collection of Configuration Endpoints
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: mstevens@atlan-tics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * a single configuration key/value with version
 */
export interface ConfigItem { 
    /**
     * The configuration key
     */
    name: string;
    /**
     * the configuration value
     */
    value: string;
    /**
     * The configuration version
     */
    version: number;
}

