/**
 * Config API
 * Collection of Configuration Endpoints
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: mstevens@atlan-tics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateVariantRequest { 
    /**
     * required by generator 
     */
    createVariantRequest: string;
    /**
     * The name of the variant that will be created. Must be unique 
     */
    variantName: string;
    /**
     * Unix timestamp for when you want this variant to activate
     */
    valid_from?: string;
    /**
     * Unix timestamp for when you want this variant to deactivate
     */
    valid_until?: string;
    /**
     * Refers to the config_id of a configuration item in the  config database that will be linked to this variant. Within the list of configIds, the configName associated with each id must be unique. (There cannot be more than one configName associated to a variant at a time. Database or interface rules must prevent this;) 
     */
    configIds: Array<number>;
}

