/**
 * Config API
 * Collection of Configuration Endpoints
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: mstevens@atlan-tics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListOfConfigsConfigListInner } from './listOfConfigsConfigListInner';


/**
 * An alphabetical list of configs sorted by name, containing an array of objects 
 */
export interface ListOfConfigs { 
    /**
     * The configuration key
     */
    configName: string;
    configList: Array<ListOfConfigsConfigListInner>;
}

